serverAddr = "your_server_addr"
serverPort = 7000
auth.method = "token"
auth.token = "123456789"

log.to = "/share/frpc.log"
# trace, debug, info, warn, error
log.level = "trace"
log.maxDays = 3

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "123456789"

[[proxies]]
name = "your_proxy_name"
type = "https"
customDomains = ["your_domain"]
transport.useEncryption = true
transport.useCompression = true
localPort = 8123
localIP = "0.0.0.0"

[proxies.plugin]
type = "https2http"
localAddr = "0.0.0.0:8123"
crtPath = "/ssl/fullchain.pem"
keyPath = "/ssl/privkey.pem"
hostHeaderRewrite = "0.0.0.0"
requestHeaders.set.x-from-where = "frp"

